### ISSUE TITLE
Render Image inside MD content

### ISSUE THREAD

**Issue by fabriciofrontarolli-uplandsoftware** [danieldunderfelt/rn-mdx#4]
Does this support image rendering?

I'm trying to render this content inside the component. It renders the text, however, it does not render the image. Doe it support image rendering?

MD Content:

```
This is a sample text for rn-mdx

![React Native Picture](https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/React-icon.svg/120px-React-icon.svg.png)
```

**Comment by fabriciofrontarolli** [comment]
I just saw the source code, inside my MD content, I saw instead of using

```
![React Native Picture](path-to-img.png)
```

I had to use

```
<img src="path-to-img.png" alt="React Native Picture" />
```

Closing this issue.
